### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by sunvim** [sam701/zig-toml#31]
please see the below picture 

![Image](https://github.com/user-attachments/assets/906616e4-24d6-482e-9096-8c31884402d1)

if move config code to another single code file, not in main entrypoint file,   memory not leak any more.

**Comment by sam701** [comment]
Could you share your config?

**Comment by sunvim** [comment]
> Could you share your config?

yes, it absolutely!

```toml
    port = 8741
    threads = 4
    workers = 2
    max_clients = 100_000
    max_body = 104857600

```
