### ISSUE TITLE
Can't parse HashMap

### ISSUE THREAD

**Issue by sirenkovladd** [sam701/zig-toml#9]
this is an example of toml
```toml
[tasks.a]
cmd = "echo 123"

[tasks.b]
cmd = "echo 123"
```
I need a possible way to parse this tasks, I can't predict the keys

Thank you
